### PR TITLE
✨ Indicator for Question Items, and frontend ability to set Question Item

### PR DESCRIPTION
**Pull request by Samad198**
image

### CODE REVIEW

**Comment by Samad198** [comment]
Now also added action to change question item
image

**Comment by Samad198** [comment]
When Question item is duplicated, the newly created item is also a question item. Should this be changed so it isn't?
Also api returns an error for duplicating page item
image

**Comment by Samad198** [comment]
Tooltip now included
image

**Review by beforan — CHANGES_REQUESTED** [review]
Some feedback to be implemented as dicussed re: moving the indicator and action buttons.

Other than that, the code itself all looks good

**Comment by Samad198** [comment]
Now moved the question icons to the left
image
image
image

**Review by beforan — APPROVED** [review]

**Pull request merged**
